#!/bin/bash
g++ src/new_ajusteh.cpp -o ajusteh
chmod +x clean
chmod +x getcalc
#chmod +x make_outputs
chmod +x runfinish
chmod +x runorig_k2

cd compare_clust
chmod +x install
./install
cd ../

cd compare_K2/
chmod +x install
./install
cd ../

cd mincode/
chmod +x install
./install
cd ../

cd converge/
chmod +x install
./install
cd ../

cd star/
chmod +x install
./install
cd ../
