#!/bin/bash
rm compare_rom/weston_ast

funx () {
	cd mincode/
	./match <<< "3"
	python3 clustermins.py $1 > ../results/$1
	cat ../results/$1
	echo $1 >> ../compare_rom/weston_ast
	cat ../results/$1 >> ../compare_rom/weston_ast
	rm minoutput
	cd ../
	rm output
	echo $1 "^^^^"
}

funt () {
        cd mincode/
        ./match <<< "3"
        python3 clustermins.py $1 > ../results/$1
        cat ../results/$1
        echo $1 >> ../compare_rom/weston_ast
        cat ../results/$1 >> ../compare_rom/weston_ast
        echo $1 >> ../compare_rom/rom_solutions
        python3 new_clustermins.py $1 >> ../compare_rom/rom_solutions
        cd contour/
        #python3 familycontour.py <<< "4"
        cd ../
        rm minoutput
        cd ../
        rm output
        echo $STAR "UP^^^"
}

func () {
        cd star/table/
        echo $1
        ./a.out <<< "$1 $2"
        cat "$1.out" >> periods_rom
        #echo "\\hline" >> periods_rom
        cd ../../
}


STAR="HS1531+7436"
func $STAR "1"

STAR="GD244"
func $STAR "1.72"

STAR="G226-29"
func $STAR "1"

STAR="HS0507+0434B"
func $STAR "7.6"

STAR="LP133-144"
func $STAR "4.0"

STAR="EC11507-1519"
func $STAR "3.59"

STAR="L19-2"
func $STAR "0.6"

STAR="GD66"
func $STAR "3.43"

STAR="G132-12"
func $STAR "4.3"

STAR="G207-9"
func $STAR "17.3"

STAR="G117-B15A"
func $STAR "6.14"

STAR="MCT2148-2911"
func $STAR "12.6"

STAR="G38-29"
func $STAR "3.07"

STAR="PG1541+650"
func $STAR "1"

STAR="G191-16"
func $STAR "1"

STAR="G185-32"
func $STAR "0.46"

STAR="EC14012-1446"
func $STAR "2.9"

STAR="EC23487-2424"
func $STAR "12.8"

STAR="GD165"
func $STAR "1"

STAR="R548"
func $STAR "0.9"

STAR="HE1258+0123"
func $STAR "9.3"

STAR="GD154"
func $STAR "0.3"

STAR="GD385"
func $STAR "3.7"

STAR="HE1429-037"
func $STAR "10.2"

STAR="HS1249+0426"
func $STAR "7.55"

STAR="G238-53"
func $STAR "9.0"

STAR="HS1625+1231"
func $STAR "7.8"

STAR="G29-38"
func $STAR "1.5"

STAR="PG2303+242"
func $STAR "7.3"

STAR="MCT0145-2211"
func $STAR "15"

STAR="BPM30551"
func $STAR "10.5"

STAR="GD99"
func $STAR "5.0"

STAR="BPM24754"
func $STAR "1"

STAR="KUV02464+3239"
func $STAR "4.0"

STAR="PG1149+058"
func $STAR "10.5"

STAR="BPM31594"
func $STAR "1"

STAR="KUV11370+4222"
func $STAR "2.5"

STAR="HS1824-6000"
func $STAR "3.30"

STAR="KUV08368+4026"
func $STAR "5.5"

STAR="R808"
func $STAR "1.99"

STAR="G255-2"
func $STAR "38"

STAR="HLTau-76"
func $STAR "2.40"

STAR="G232-38"
func $STAR "1.9"

STAR="G30-20"
func $STAR "13.8"


